#修改项目名
server:
  servlet:
    context-path: /vote
#设置templates的路径，放行静态资源，数据库连接
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myvote?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.flower.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full
    use-generated-keys: true
pagehelper:
  page-size-zero: true
  reasonable: true
